version: '3'

services:
  mongo:
    image: mongo:4
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: local
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: